FROM golang:1.21 as build
WORKDIR /app
ADD ../../../ .
RUN go build main.go
FROM golang:alpine
WORKDIR /app
COPY --from=build /app/main .
RUN mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2
EXPOSE 3000
CMD ["./main"]