apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-alias.allow-tags: 'regexp:^1.3.0-SNAPSHOT.[0-9]+$'
    argocd-image-updater.argoproj.io/image-alias.force-update: 'true'
    argocd-image-updater.argoproj.io/image-alias.update-strategy: latest
  name: p2p-devops-test-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/akatruk/p2p-devops-test
    path: devops
    targetRevision: staging
    helm:
      valueFiles: 
        - values-stg.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: p2p-devops-test-staging

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      
    automated:
      prune: true
      selfHeal: true
      