name: "run go tests"

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ develop ]

jobs:
  dev-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Run Unit & Integration Tests
        run: go test main_test.go