name: Security Testing

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  pull_request:
    types: [opened, synchronize]

jobs:
  sast:
    uses: ./.github/security/sast.yaml
    secrets: inherit
  sca:
    uses: ./.github/security/sca.yaml
    secrets: inherit
