name: Security Testing

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  pull_request:
    types: [opened, synchronize]

jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/security/sast.yaml

  sca:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/security/sca.yaml
